# version: '3.9'
services:
  api:
    container_name: api
    build: ./api
    ports:
      - 8080:8080
    # docker container run -t ubuntu bash の t オプション => 標準入力とbashの入力を繋げる
    tty: true
    volumes:
      # docker-compose 内は相対パス ok
      # "cached" はオプションで、同期精度よりもスピード重視する
      - ./api:/workspace:cached

  web:
    container_name: web
    build: 
      context: ./web
      target: base
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    tty: true
    volumes:
      - ./web:/workspace:cached
    depends_on:
      - api